### ISSUE TITLE
Can't Send Email in Prod

### ISSUE THREAD

**Issue by taylorbrooks** [DockYard/courier#26]
I know this is probably something really stupid that I'm overlooking...

I am able to send email when running my app locally, but not after deploying.

This is the error I get: 
````elixir
01:22:12.077 [error] Process #PID<0.6419.0> raised an exception
** (FunctionClauseError) no function clause matching in :base64.encode/1
    (stdlib) base64.erl:64: :base64.encode(nil)
    src/gen_smtp_client.erl:375: :gen_smtp_client.do_AUTH_each/4
    src/gen_smtp_client.erl:322: :gen_smtp_client.try_AUTH/3
    src/gen_smtp_client.erl:203: :gen_smtp_client.do_smtp_session/3
    src/gen_smtp_client.erl:142: :gen_smtp_client.try_smtp_sessions/4
    src/gen_smtp_client.erl:109: :gen_smtp_client.send_it_nonblock/3
** (EXIT from #PID<0.1695.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :base64.encode/1
        (stdlib) base64.erl:64: :base64.encode(nil)
        src/gen_smtp_client.erl:375: :gen_smtp_client.do_AUTH_each/4
        src/gen_smtp_client.erl:322: :gen_smtp_client.try_AUTH/3
        src/gen_smtp_client.erl:203: :gen_smtp_client.do_smtp_session/3
        src/gen_smtp_client.erl:142: :gen_smtp_client.try_smtp_sessions/4
        src/gen_smtp_client.erl:109: :gen_smtp_client.send_it_nonblock/3
````

This is my `config/confix.exs':
````elixir
config :drip_emails, DripEmails.Mailer,
  adapter: Courier.Adapters.SMTP,
  relay: "email-smtp.us-east-1.amazonaws.com",
  port: 587,
  username: System.get_env("AWS_SMTP_USER"),
  password: System.get_env("AWS_SMTP_PASS")
````

This is my `mix.lock` for Courier:
````elixir
 "courier": {:hex, :courier, "0.0.3", "a01a42d3c06b08989bc1003acd5a58db1c652b4c6ecb414286f70b8ca62a67ec", [:mix], [{:gen_smtp, "0.9.0", [hex: :gen_smtp, optional: false]}, {:mail, "~> 0.0.4", [hex: :mail, optional: false]}]}
````

The way I'm reading these errors, its as if :gen_smtp can't parse the username / password because they aren't set. But when I inspect the values of those AWS_SMTP_*** env vars, they are clearly set.

Again, everything works fine locally, but not after deploying on Heroku.

Any thoughts?

**Comment by bcardarella** [comment]
@taylorbrooks can you try `master` instead of `0.0.3`?

**Comment by taylorbrooks** [comment]
Different error locally: 
````elixir
** (exit) exited in: GenServer.call(Courier.Stores.Simple, {:update, #Function<4.11953483/1 in Courier.Stores.Simple.put/1>}, 5000)
  ** (EXIT) no process
  (elixir) lib/gen_server.ex:596: GenServer.call/3
````

**Comment by taylorbrooks** [comment]
Heroku Buildpacks:
https://github.com/HashNuke/heroku-buildpack-elixir
https://github.com/taylorbrooks/heroku-buildpack-phoenix-static

````elixir
 02:33:10.408 [error] GenServer #PID<0.23670.1> terminating
** (FunctionClauseError) no function clause matching in :gen_smtp_client.to_string/1
    (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:337: :gen_smtp_client.to_string(nil)
    (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:319: :gen_smtp_client.try_AUTH/3
    (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:203: :gen_smtp_client.do_smtp_session/3
    (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:142: :gen_smtp_client.try_smtp_sessions/4
    (courier) lib/courier/scheduler.ex:111: Courier.Scheduler.Worker.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
02:33:10.409 [error] Task #PID<0.24614.1> started from #PID<0.423.0> terminating
** (stop) exited in: GenServer.call(#PID<0.23670.1>, {:deliver, %Mail.Message{body: nil, headers: %{"date" => {{2016, 10, 27}, {2, 33, 9}}, "from" => "hello@dripemails.com", "subject" => "BLOCKED Drip for taylor@simpledonation.com", "to" => ["taylor@dripemails.com"]}, multipart: true, parts: [%Mail.Message{body: "bingbong", headers: %{"content-transfer-encoding" => :quoted_printable, "content-type" => "text/plain"}, multipart: false, parts: []}]}, [relay: "email-smtp.us-east-1.amazonaws.com", port: 587, username: nil, password: nil, adapter: Courier.Adapters.SMTP, mailer: DripEmails.Mailer, sent_from: #PID<0.437.0>]}, :infinity)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :gen_smtp_client.to_string/1
            (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:337: :gen_smtp_client.to_string(nil)
            (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:319: :gen_smtp_client.try_AUTH/3
            (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:203: :gen_smtp_client.do_smtp_session/3
            (gen_smtp) /tmp/build_06b069f49fa1d9fd91ff8378e3821b73/deps/gen_smtp/src/gen_smtp_client.erl:142: :gen_smtp_client.try_smtp_sessions/4
            (courier) lib/courier/scheduler.ex:111: Courier.Scheduler.Worker.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (poolboy) src/poolboy.erl:76: :poolboy.transaction/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<1.130140455/0 in Courier.Scheduler.handle_info/2>
    Args: []
```

**Comment by taylorbrooks** [comment]
Figured it out. 

[elixir_buildpack.config](https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/elixir_buildpack.config)

Should have env vars exported:
`config_vars_to_export=(DATABASE_URL AWS_USER AWS_PASSWORD)`
